version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboard_db
    ports:
      - '5432:5432'