version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/user-registration
  mongo:
    image: mongo
    ports:
      - '27017:27017'