
services:
  - type: web
    name: backend-service
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn Web Server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
